### PR TITLE
VRZN Homepage

### PR DESCRIPTION
**Pull request by Galope-Jhean**
Adding VRZN Homepage to this repository, this PR is consisted of 

- index.html 
- style.css
- images folder
- readme documentation

### CODE REVIEW

**Review by go-christianharrel — APPROVED** [review]
### LGTM! :>

**Review by Naoe-Adrian — APPROVED** [review]
LGTM 💯🥇

**Review by Odrunia-Mark-Ryan — APPROVED** [review]

**Review by Dimasacat-Andronicus — APPROVED** [review]
For me, it's already okay.

**Review by go-christianharrel — APPROVED** [review]
I partially removed the github pages for this repository!

**Review by Naoe-Adrian — APPROVED** [review]
This make sense 🖤 since rn we don't have our deploy github pages.

**Review by Odrunia-Mark-Ryan — APPROVED** [review]

**Review by Dimasacat-Andronicus — APPROVED** [review]

**Pull request merged**
